baseURL = 'https://shaylyu.github.io/Blog/'
title = 'My New Hugo Site'
theme = "dream"
defaultContentLanguage = "zh"
languageCode = "zh-Hans"


[params]
# zenMode = true
lightTheme = "emerald"
darkTheme = "forest"
footerBottomText = "<div class='text-sm text-base-content/60'>采用 CC BY-NC 4.0 许可证发布</div>"
rss = true
motto = "繁星纵变 智慧永恒"
author = "Shay"
headerTitle = "Shay"
avatar = "https://cdn.jsdelivr.net/gh/ShayLyu/logo@main/avatar.jpg"
favicon = "https://cdn.jsdelivr.net/gh/ShayLyu/logo@main/avatar-round.png"
siteStartYear = 2024
email = "liushanhui9@gmail.com"
description = "Shay的私人窝点"
stickyNav = true
reorderNavItems = ["github", "search", "rss", "posts", "categories", "tags"]
collapseNavItems = ["posts", "categories", "tags", "rss"]
customSyntaxHighlighting = true
#waline = true
#walineServer = "waline.ricolxwz.io"
[params.navItems]
github = { href = "https://github.com/ShayLyu", target = "_blank", icon = "logo-github", title = "GitHub" }

[params.experimental]
jsDate = true
jsDateFormat = "yyyy年MM月dd日"